// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandyMan.Models
{
    [Table("Client")]
    [Index("Client_Mobile", Name = "UQ__Client__409D25A0AB59A5F9", IsUnique = true)]
    public partial class Client
    {
        public Client()
        {
            Requests = new HashSet<Request>();
        }

        [Key]
        public int Client_ID { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [StringLength(50, ErrorMessage = "Name can't be longer than 50 characters")]
        [Unicode(false)]
        public string Client_name { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Client_Email { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [StringLength(100, ErrorMessage = "Address cannot be longer than 100 characters")]
        [Unicode(false)]
        public string Client_Address { get; set; }
        [Required(ErrorMessage = "Mobile is required")]
        [RegularExpression(@"^([0-9]{11})$", ErrorMessage = "Invalid Mobile Number.")]
        [StringLength(11)]
        [Unicode(false)]
        public string Client_Mobile { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }

        public int Region_ID { get; set; }

        [ForeignKey("Region_ID")]
        [InverseProperty("Clients")]
        public virtual Region? Region { get; set; }
        [InverseProperty("Client")]
        public virtual ICollection<Request>? Requests { get; set; }

        [NotMapped]
        [Range(-99, 99)]
        public double? Balance { get; set; }

        [NotMapped]
        [Range(1, 5)]
        public double? Rating { get; set; }
    }
}