// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandyMan.Models
{
    [Table("Client")]
    [Index("Client_Mobile", Name = "UQ__Client__409D25A0AB59A5F9", IsUnique = true)]
    public partial class Client
    {
        public Client()
        {
            Requests = new HashSet<Request>();
        }

        [Key]
        public int Client_ID { get; set; }
        [Required]
        [StringLength(50)]
        public string Client_name { get; set; }

        [Required]
        [StringLength(50)]
        public string Client_Email { get; set; }

        [Required]
        [StringLength(100)]
        public string Client_Address { get; set; }

        [Required]
        [StringLength(11)]
        public string Client_Mobile { get; set; }

        [StringLength(50)]
        public string Password { get; set; }

        public int Region_ID { get; set; } = 0;

        [ForeignKey("Region_ID")]
        [InverseProperty("Clients")]
        public virtual Region? Region { get; set; }

        [InverseProperty("Client")]
        public virtual ICollection<Request>? Requests { get; set; }


        [Range(-99, 99)]
        public int? Balance { get; set; } = 0;

        [NotMapped]
        [Range(1, 5)]
        public double? Rating { get; set; }
    }
}