// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandyMan.Models
{
    [Table("Craft")]
    public partial class Craft
    {
        public Craft()
        {
            Handymen = new HashSet<Handyman>();
        }

        [Key]
        public int Craft_ID { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Craft_Name { get; set; }

        [InverseProperty("Craft")]
        public virtual ICollection<Handyman> Handymen { get; set; }
    }
}