// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandyMan.Models
{
    [Table("Region")]
    public partial class Region
    {
        public Region()
        {
            Clients = new HashSet<Client>();
            Handyman_SSNs = new HashSet<Handyman>();
        }

        [Key]
        public int Region_ID { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Region_Name { get; set; }

        [InverseProperty("Region")]
        public virtual ICollection<Client>? Clients { get; set; }

        [ForeignKey("Region_ID")]
        [InverseProperty("Regions")]
        public virtual ICollection<Handyman>? Handyman_SSNs { get; set; }
    }
}