// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandyMan.Models
{
    [Table("Schedule")]
    public partial class Schedule
    {
        [Key]
        public int Handy_SSN { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime Schedule_Date { get; set; }
        [Key]
        public TimeSpan Time_From { get; set; }
        public TimeSpan Time_To { get; set; }

        [ForeignKey("Handy_SSN")]
        [InverseProperty("Schedules")]
        public virtual Handyman Handy_SSNNavigation { get; set; }
    }
}